#!/bin/bash
echo not a script
exit 1

# check whether csv generated by ccc is sane
pigz -d < ../raw-data/everything-csv-ver2.csv.gz | iconv -f sjis | grep -E '^Circle,' | while IFS= read -r x; do nc="$(printf '%s\n' "$x" | tr -dc ',\n' | wc -c)"; printf '%s %s\n' $nc "$x"; done | tee .commas | grep -vE '^(29|30|31) ' | sed -r "$(printf 's/,/\033[1;37;41m,\033[0m/g')"

